[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "torchgear"
version = "0.1.0"
description = "Utility extensions for PyTorch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.0",
]

[tool.setuptools.packages.find]
where = ["src"]
